USE [master]
GO

/****** Object:  Database [DSQL]    Script Date: 9/19/2025 10:55:38 AM ******/
CREATE DATABASE [DSQL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TBMoi', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\2a7ede63-4b9a-42b5-ba0f-91f065f37800_1_7ba6b85d-821c-44c7-af68-7409260f702a_1_QTU.mdf' , SIZE = 89664KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TBMoi_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\2a7ede63-4b9a-42b5-ba0f-91f065f37800_2_7ba6b85d-821c-44c7-af68-7409260f702a_2_QTU123_log.ldf' , SIZE = 149696KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DSQL].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [DSQL] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DSQL] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DSQL] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DSQL] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DSQL] SET ARITHABORT OFF 
GO

ALTER DATABASE [DSQL] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DSQL] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DSQL] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DSQL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DSQL] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DSQL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DSQL] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DSQL] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DSQL] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DSQL] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DSQL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DSQL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DSQL] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DSQL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DSQL] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DSQL] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DSQL] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DSQL] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DSQL] SET  MULTI_USER 
GO

ALTER DATABASE [DSQL] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DSQL] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DSQL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DSQL] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DSQL] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DSQL] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DSQL] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DSQL] SET  READ_WRITE 
GO

